<?php
    session_start();
    $action = $this->getAction();
?>

<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.0/jquery.min.js"></script>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <link rel="stylesheet" href="/styles.css">
    <script src="https://kit.fontawesome.com/ffd879fa2f.js" crossorigin="anonymous"></script>
</head>
<body>
<ul class="nav justify-content-center py-4">
    <li class="nav-item ">
        <a class="nav-link" href="/home/index">
            <h2>Home</h2>
        </a>
    </li>
    <li class="nav-item">
        <a class="nav-link" href="/country/index/">
            <h2>Countries</h2>
        </a>
    </li>
</ul>
</body>


